# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/real_constraints.xdc

# Block Designs: bd/zynq_processor/zynq_processor.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_processor || ORIG_REF_NAME==zynq_processor} -quiet] -quiet

# IP: bd/zynq_processor/ip/zynq_processor_processing_system7_0_0/zynq_processor_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_processor_processing_system7_0_0 || ORIG_REF_NAME==zynq_processor_processing_system7_0_0} -quiet] -quiet

# IP: ip/gtwizard_0/gtwizard_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gtwizard_0 || ORIG_REF_NAME==gtwizard_0} -quiet] -quiet

# XDC: c:/Users/huhug/FPGA_workspace/Doutoramento/ZC706_start/GTX_implementation_tests/OTHER/gtwizard_0_ex/gtwizard_0_ex.gen/sources_1/bd/zynq_processor/zynq_processor_ooc.xdc

# XDC: c:/Users/huhug/FPGA_workspace/Doutoramento/ZC706_start/GTX_implementation_tests/OTHER/gtwizard_0_ex/gtwizard_0_ex.gen/sources_1/ip/gtwizard_0/gtwizard_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==gtwizard_0 || ORIG_REF_NAME==gtwizard_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/huhug/FPGA_workspace/Doutoramento/ZC706_start/GTX_implementation_tests/OTHER/gtwizard_0_ex/gtwizard_0_ex.gen/sources_1/ip/gtwizard_0/gtwizard_0_ooc.xdc
