# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/huhug/FPGA_workspace/Doutoramento/ZC706_start/GTX_implementation_tests/OTHER/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/bd/zynq_processor/ip/zynq_processor_processing_system7_0_0/zynq_processor_processing_system7_0_0.xci
# IP: The module: 'zynq_processor_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/huhug/FPGA_workspace/Doutoramento/ZC706_start/GTX_implementation_tests/OTHER/gtwizard_0_ex/gtwizard_0_ex.gen/sources_1/bd/zynq_processor/ip/zynq_processor_processing_system7_0_0/zynq_processor_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_processor_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/huhug/FPGA_workspace/Doutoramento/ZC706_start/GTX_implementation_tests/OTHER/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/bd/zynq_processor/ip/zynq_processor_processing_system7_0_0/zynq_processor_processing_system7_0_0.xci
# IP: The module: 'zynq_processor_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/huhug/FPGA_workspace/Doutoramento/ZC706_start/GTX_implementation_tests/OTHER/gtwizard_0_ex/gtwizard_0_ex.gen/sources_1/bd/zynq_processor/ip/zynq_processor_processing_system7_0_0/zynq_processor_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_processor_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
